services:
  place-wrapper:
    build: .
    container_name: place-wrapper
    environment:
      - ENV_VAR=example
      - REDIS_HOST=places_wrapper_cache
      - REDIS_PORT=6379
    volumes:
      # - .:/app
      - .:/app:Z
    depends_on:
      - place_wrapper_cache

  place_wrapper_cache:
    image: "redis:alpine"
    container_name: places_wrapper_cache
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
